import type { Metadata } from "next";
import "@/app/globals.scss";
import Header from "@/component/molecules/Header";
import AppWrapper from "./AppWrapper";
import { eduNswActCursive, zenMaruGothic } from "@/const/font/font";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${eduNswActCursive.variable} ${zenMaruGothic.variable}`}
      >
        <AppWrapper>
          <Header />
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
