export const METADATA = (siteName: string) => ({
  TITLE: {
    HOME: "TOP",
    REGULATION: "レギュレーション",
    RACE: "種族",
    SUPPLEMENT: "使用サプリ",
    GOD: "信仰",
    SCHOOL: "流派",
    HOUSE_RULE: "ハウスルール",
    ORIGINAL: "オリジナルデータ",
    PERIOD_LIST: "レギュレーション一覧",
    WORD: "語録",
    STAGE_TERM: "舞台/用語",
    LEVEL_CAP: "レベルキャップ",
  },
  DESCRIPTION: {
    HOME: `${siteName} - TRPGコミュニティポータル`,
    REGULATION: `${siteName} - レギュレーション詳細`,
    RACE: `${siteName} - 使用可能種族一覧`,
    SUPPLEMENT: `${siteName} - 使用サプリ一覧`,
    GOD: `${siteName} - 信仰一覧`,
    SCHOOL: `${siteName} - 流派一覧`,
    HOUSE_RULE: `${siteName} - ハウスルール`,
    ORIGINAL: `${siteName} - オリジナルデータ`,
    PERIOD_LIST: `${siteName} - レギュレーション一覧`,
    WORD: `${siteName} - 語録`,
    STAGE_TERM: `${siteName} - 舞台/用語`,
    LEVEL_CAP: `${siteName} - レベルキャップ`,
  },
});
