export const METADATA = {
  TITLE: {
    HOME: "TOP",
    REGULATION: "レギュレーション",
    RACE: "種族",
    SUPPLEMENT: "使用サプリ",
    GOD: "信仰",
    SCHOOL: "流派",
    HOUSE_RULE: "ハウスルール",
    PROHIBITION: "使用禁止アイテム",
    ORIGINAL: "オリジナルデータ",
    PERIOD_LIST: "レギュレーション一覧",
    WORD: "語録",
    STAGE_TERM: "舞台/用語",
    LEVEL_CAP: "レベルキャップ",
  },
  DESCRIPTION: {
    HOME: "隻翼の大鷲亭 - TRPGコミュニティポータル",
    REGULATION: "隻翼の大鷲亭 - レギュレーション詳細",
    RACE: "隻翼の大鷲亭 - 使用可能種族一覧",
    SUPPLEMENT: "隻翼の大鷲亭 - 使用サプリ一覧",
    GOD: "隻翼の大鷲亭 - 信仰一覧",
    SCHOOL: "隻翼の大鷲亭 - 流派一覧",
    HOUSE_RULE: "隻翼の大鷲亭 - ハウスルール",
    PROHIBITION: "隻翼の大鷲亭 - 使用禁止アイテム",
    ORIGINAL: "隻翼の大鷲亭 - オリジナルデータ",
    PERIOD_LIST: "隻翼の大鷲亭 - レギュレーション一覧",
    WORD: "隻翼の大鷲亭 - 語録",
    STAGE_TERM: "隻翼の大鷲亭 - 舞台/用語",
    LEVEL_CAP: "隻翼の大鷲亭 - レベルキャップ",
  },
};
