import type { EntityConfigType, LevelCapScheduleItem } from "@/const/type/config/EntityConfigType";

export const regulationConfig: EntityConfigType = {
  apiType: "regulation",
  listTitle: "レギュレーション管理",
  addLabel: "レギュレーションを追加",
  editTitle: "レギュレーションを編集",
  deleteConfirm: "このレギュレーションを削除しますか？",
  initialForm: {
    name: "",
    description: "",
    recruitment: "",
    stage: "",
    levelCapBelt: "B",
    charCreationStartDate: "",
    epilogueStartDate: "",
    epilogueEndDate: "",
    levelCapSchedule: [],
    publishType: "draft",
    godIds: [],
    schoolIds: [],
    raceIds: [],
    supplementIds: [],
    notes: "",
  },
  columns: [
    { key: "id", label: "ID" },
    { key: "name", label: "名前" },
    {
      key: "publish_type",
      label: "公開状態",
      render: (v) => (v === "public" ? "公開" : "下書き"),
    },
  ],
  formItems: [
    {
      column: "publishType",
      label: "公開状態",
      type: "select",
      rule: { required: true },
      option: [
        { label: "下書き", value: "draft" },
        { label: "公開", value: "public" },
      ],
    },
    { column: "name", label: "名前", type: "text", rule: { required: true } },
    { column: "description", label: "説明", type: "textarea" },
    { column: "recruitment", label: "募集内容", type: "textarea" },
    { column: "stage", label: "舞台設定", type: "textarea" },
    {
      column: "levelCapBelt",
      label: "レベルキャップ帯",
      type: "select",
      rule: { required: true },
      option: [
        { label: "B", value: "B" },
        { label: "C", value: "C" },
      ],
    },
    { column: "godIds", label: "使用可能神格", type: "checkbox-group" },
    { column: "schoolIds", label: "使用可能流派", type: "checkbox-group" },
    { column: "raceIds", label: "使用可能種族", type: "checkbox-group" },
    { column: "supplementIds", label: "使用可能サプリメント", type: "checkbox-group" },
    { column: "notes", label: "備考", type: "textarea" },
    { column: "_schedule", label: "スケジュール", type: "section-heading" },
    { column: "charCreationStartDate", label: "キャラ作成開始日", type: "date" },
    { column: "levelCapSchedule", label: "レベルキャップ日程", type: "level-cap-schedule" },
    { column: "epilogueStartDate", label: "エピローグ期間", type: "epilogue-period" },
  ],
  toForm: (data) => ({
    publishType: data.publish_type,
    name: data.name,
    description: data.description,
    recruitment: data.recruitment,
    stage: data.stage,
    levelCapBelt: data.level_cap_belt,
    charCreationStartDate: (data.char_creation_start_date as string) ?? "",
    epilogueStartDate: (data.epilogue_start_date as string) ?? "",
    epilogueEndDate: (data.epilogue_end_date as string) ?? "",
    levelCapSchedule: (data.level_cap_schedule as LevelCapScheduleItem[]) ?? [],
    godIds: data.godIds ?? [],
    schoolIds: data.schoolIds ?? [],
    raceIds: data.raceIds ?? [],
    supplementIds: data.supplementIds ?? [],
    notes: data.notes,
  }),
  toBody: (form) => form,
  previewBasePath: "/regulation",
};
